# Generated by Django 2.0.4 on 2018-04-25 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Verified', models.BooleanField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_1', models.TextField(max_length=500)),
                ('Task_2', models.TextField(max_length=500)),
                ('Task_3', models.TextField(max_length=500)),
                ('Task_4', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=300)),
                ('Age', models.IntegerField(max_length=4)),
                ('Email', models.EmailField(max_length=250)),
                ('Roles', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='scrumyuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayodescrumy.ScrumyUser'),
        ),
    ]
