# Generated by Django 2.0.4 on 2018-04-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayodescrumy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoalStatus',
        ),
        migrations.RemoveField(
            model_name='scrumyuser',
            name='Roles',
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='Age',
            field=models.IntegerField(default=0),
        ),
    ]
