# Generated by Django 2.0.4 on 2018-04-29 01:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bayodescrumy', '0002_auto_20180425_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('V', 'Verified')], max_length=50)),
                ('completed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('goals', models.CharField(choices=[('W', 'Weekly Goals'), ('DA', 'Daily Task')], default='DA', max_length=100, null=True)),
                ('verified_by', models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('D', 'Developer'), ('QA', 'Quality Analyst')], default='QA', max_length=30)),
                ('verified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default="It's not easy", max_length=100)),
                ('task', models.TextField()),
                ('task_id', models.IntegerField(default=400)),
                ('moved_by', models.CharField(default='not moved', max_length=50)),
                ('created_by', models.CharField(default='O', max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_of_status_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('goalstatus_id', models.ForeignKey(blank=True, default=400, null=True, on_delete=django.db.models.deletion.PROTECT, to='bayodescrumy.GoalStatus')),
            ],
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='Task_1',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='Task_2',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='Task_3',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='Task_4',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='scrumyuser',
        ),
        migrations.RemoveField(
            model_name='scrumyuser',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='scrumyuser',
            name='Email',
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='Name',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='scrumyuser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bayodescrumy.ScrumyUser'),
        ),
    ]
