# Generated by Django 2.0.4 on 2018-04-29 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bayodescrumy', '0003_auto_20180429_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalstatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='goalstatus_id',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='moved_by',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='scrumyuser_id',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='task',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='time_of_status_change',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='title',
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='created_by',
            field=models.CharField(default='O', max_length=50),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='goalstatus',
            field=models.ForeignKey(blank=True, default=400, null=True, on_delete=django.db.models.deletion.PROTECT, to='bayodescrumy.GoalStatus'),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='moved_by',
            field=models.CharField(default='not moved', max_length=50),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='scrumyuser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bayodescrumy.ScrumyUser'),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='task',
            field=models.CharField(default='enter your task', max_length=100),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='task_id',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='time_of_status_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='title',
            field=models.CharField(default="It's not easy", max_length=100),
        ),
    ]
